root = "."
tmp_dir = "tmp"

[build]
  bin = "./bin/raino"
  # remember to generate templ BEFORE building and serving
  cmd = """
    CGO_ENABLED=1 GOOS=linux \
      go build -o ./bin/raino ./cmd
  """
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules", "logs"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  # include all file extension to follow
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "js"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
